[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#lexical_scanner =  { git = "https://github.com/mjehrhart/lexical_scanner", branch = "master" }
eframe = "0.17.0"
egui = "0.17.0"
egui_extras = { version = "0.17.0", features = ["image", "svg"] }  
image = { version = "0.24.1", default-features = false, features = ["png"] }