[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lexical_scanner =  { git = "https://github.com/mjehrhart/lexical_scanner", branch = "master" }
 
eframe = "0.17.0"
egui = "0.17.0"
egui_extras = { version = "0.17.0", features = ["image", "svg"] }  
image = { version = "0.24.1", default-features = false, features = ["png"] }
futures = "0.3" # for our async / await blocks
tokio = { version = "1.16.0", features = ["full"] } 
rayon = "1.4.1"
walkdir = "2"
regex = "1"
chrono = "0.4"
md5 = "0.7.0"
blake3 = "1.3.1"
jwalk = "0.5"
rfd = "0.7.0"
byte-unit = "4.0.3"
fuzzy-matcher = "0.3.7" 
home = "0.5.3"